from models import CourseModule, ResourceLink

COURSE_CATALOG: list[CourseModule] = [
    # ── PYTHON ──────────────────────────────────────────────────────────────────
    CourseModule(
        id="python-fund-001",
        title="Python Fundamentals",
        skill_name="python",
        category="programming_language",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=[],
        learning_objectives=[
            "Understand Python syntax and data types",
            "Write functions and use control flow",
            "Work with lists, dicts, and tuples",
            "Handle exceptions and file I/O",
        ],
        resources=[
            ResourceLink(title="Python Official Tutorial", url="https://docs.python.org/3/tutorial/", type="docs"),
            ResourceLink(title="Python for Beginners – Microsoft", url="https://www.youtube.com/watch?v=jFCNu1-Xdsw", type="video"),
            ResourceLink(title="CS50P – Introduction to Python", url="https://cs50.harvard.edu/python/2022/", type="course"),
        ],
        description="Core Python programming covering syntax, data structures, functions, and error handling.",
        job_market_relevance="Required in 82% of backend and data science job postings.",
        unlocks=["fastapi", "django", "machine learning", "pandas & numpy", "data visualization"],
    ),
    CourseModule(
        id="python-int-002",
        title="Python Intermediate",
        skill_name="python",
        category="programming_language",
        difficulty="Intermediate",
        duration_hours=5.0,
        prerequisites=["python-fund-001"],
        learning_objectives=[
            "Master OOP principles in Python",
            "Use decorators, generators, and context managers",
            "Write async/await coroutines",
            "Apply type hints throughout a codebase",
        ],
        resources=[
            ResourceLink(title="Real Python – Intermediate Python Tutorials", url="https://realpython.com/tutorials/intermediate/", type="article"),
            ResourceLink(title="Fluent Python – O'Reilly", url="https://www.oreilly.com/library/view/fluent-python-2nd/9781492056348/", type="course"),
            ResourceLink(title="Python Async IO In Practice", url="https://www.youtube.com/watch?v=iG6fr81xHKA", type="video"),
        ],
        description="Intermediate Python: OOP, decorators, generators, async programming, and type hints.",
        job_market_relevance="Required in 74% of backend engineering roles.",
        unlocks=["fastapi", "django", "machine learning", "llm api integration"],
    ),
    CourseModule(
        id="python-adv-003",
        title="Python Advanced",
        skill_name="python",
        category="programming_language",
        difficulty="Advanced",
        duration_hours=6.0,
        prerequisites=["python-int-002"],
        learning_objectives=[
            "Implement design patterns in Python",
            "Profile and optimize performance-critical code",
            "Write comprehensive test suites (pytest)",
            "Build and publish Python packages",
        ],
        resources=[
            ResourceLink(title="Advanced Python Mastery – David Beazley", url="https://github.com/dabeaz-course/python-mastery", type="course"),
            ResourceLink(title="Python Testing with pytest", url="https://realpython.com/pytest-python-testing/", type="article"),
            ResourceLink(title="Python Performance Tips", url="https://www.youtube.com/watch?v=YjHsOrOOSuI", type="video"),
        ],
        description="Advanced Python: design patterns, performance optimization, testing, and packaging.",
        job_market_relevance="Required in 61% of senior Python engineer postings.",
        unlocks=["fastapi", "machine learning", "deep learning basics"],
    ),
    # ── JAVASCRIPT / TYPESCRIPT ─────────────────────────────────────────────────
    CourseModule(
        id="js-ess-004",
        title="JavaScript Essentials",
        skill_name="javascript",
        category="programming_language",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=[],
        learning_objectives=[
            "Understand the JavaScript event loop and scope",
            "Work with ES6+ features (arrow functions, destructuring, spread)",
            "Use Promises and async/await",
            "Manipulate the DOM",
        ],
        resources=[
            ResourceLink(title="JavaScript.info – Modern JS Tutorial", url="https://javascript.info/", type="article"),
            ResourceLink(title="MDN JavaScript Guide", url="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide", type="docs"),
            ResourceLink(title="Fireship JS in 100 Seconds", url="https://www.youtube.com/watch?v=DHjqpvDnNGE", type="video"),
        ],
        description="Modern JavaScript fundamentals including ES6+, async patterns, and DOM manipulation.",
        job_market_relevance="Required in 88% of frontend and full-stack job postings.",
        unlocks=["typescript basics", "react fundamentals", "node.js fundamentals"],
    ),
    CourseModule(
        id="ts-basics-005",
        title="TypeScript Basics",
        skill_name="typescript",
        category="programming_language",
        difficulty="Intermediate",
        duration_hours=3.0,
        prerequisites=["js-ess-004"],
        learning_objectives=[
            "Add static typing to JavaScript codebases",
            "Use interfaces, enums, and generics",
            "Configure tsconfig.json",
            "Integrate TypeScript with React",
        ],
        resources=[
            ResourceLink(title="TypeScript Official Handbook", url="https://www.typescriptlang.org/docs/handbook/intro.html", type="docs"),
            ResourceLink(title="TypeScript Full Course – Traversy Media", url="https://www.youtube.com/watch?v=30LWjhZzg50", type="video"),
            ResourceLink(title="TypeScript Deep Dive", url="https://basarat.gitbook.io/typescript/", type="article"),
        ],
        description="TypeScript fundamentals: static typing, interfaces, generics, and tooling setup.",
        job_market_relevance="Required in 67% of frontend/full-stack engineering roles.",
        unlocks=["react advanced"],
    ),
    # ── SQL ─────────────────────────────────────────────────────────────────────
    CourseModule(
        id="sql-fund-006",
        title="SQL Fundamentals",
        skill_name="sql",
        category="tool",
        difficulty="Beginner",
        duration_hours=3.0,
        prerequisites=[],
        learning_objectives=[
            "Write SELECT, INSERT, UPDATE, DELETE queries",
            "Use JOINs to combine tables",
            "Apply aggregate functions and GROUP BY",
            "Understand indexes and basic query planning",
        ],
        resources=[
            ResourceLink(title="SQLZoo – Interactive SQL Tutorial", url="https://sqlzoo.net/wiki/SQL_Tutorial", type="course"),
            ResourceLink(title="Mode Analytics SQL Tutorial", url="https://mode.com/sql-tutorial/", type="article"),
            ResourceLink(title="SQL for Data Science – Coursera", url="https://www.coursera.org/learn/sql-for-data-science", type="course"),
        ],
        description="Core SQL: querying, joins, aggregations, and indexing fundamentals.",
        job_market_relevance="Required in 79% of backend and data engineering roles.",
        unlocks=["sql advanced", "data visualization", "statistics for ds"],
    ),
    CourseModule(
        id="sql-adv-007",
        title="SQL Advanced",
        skill_name="sql",
        category="tool",
        difficulty="Advanced",
        duration_hours=4.0,
        prerequisites=["sql-fund-006"],
        learning_objectives=[
            "Write complex window functions and CTEs",
            "Optimize slow queries with EXPLAIN ANALYZE",
            "Design normalized and denormalized schemas",
            "Work with stored procedures and transactions",
        ],
        resources=[
            ResourceLink(title="Advanced SQL – Mode Analytics", url="https://mode.com/sql-tutorial/sql-window-functions/", type="article"),
            ResourceLink(title="Use the Index, Luke", url="https://use-the-index-luke.com/", type="article"),
            ResourceLink(title="PostgreSQL Tutorial – Advanced", url="https://www.postgresqltutorial.com/postgresql-window-function/", type="docs"),
        ],
        description="Advanced SQL: window functions, CTEs, query optimization, and schema design.",
        job_market_relevance="Required in 54% of senior backend and data engineering postings.",
        unlocks=["statistics for ds"],
    ),
    # ── JAVA ───────────────────────────────────────────────────────────────────
    CourseModule(
        id="java-core-008",
        title="Java Core",
        skill_name="java",
        category="programming_language",
        difficulty="Beginner",
        duration_hours=5.0,
        prerequisites=[],
        learning_objectives=[
            "Understand JVM and Java syntax",
            "Work with collections framework",
            "Handle exceptions and use streams",
            "Write unit tests with JUnit",
        ],
        resources=[
            ResourceLink(title="Java Programming MOOC – Helsinki University", url="https://java-programming.mooc.fi/", type="course"),
            ResourceLink(title="Java Documentation – Oracle", url="https://docs.oracle.com/en/java/", type="docs"),
            ResourceLink(title="Amigoscode Java Full Course", url="https://www.youtube.com/watch?v=Qgl81fPcLc8", type="video"),
        ],
        description="Java fundamentals: syntax, collections, exception handling, and testing.",
        job_market_relevance="Required in 71% of enterprise backend and Android development roles.",
        unlocks=["java oop", "spring boot basics"],
    ),
    CourseModule(
        id="java-oop-009",
        title="Java OOP",
        skill_name="java",
        category="programming_language",
        difficulty="Intermediate",
        duration_hours=4.0,
        prerequisites=["java-core-008"],
        learning_objectives=[
            "Apply SOLID principles",
            "Use design patterns (Factory, Observer, Strategy)",
            "Understand Java generics and interfaces",
            "Work with Java concurrency basics",
        ],
        resources=[
            ResourceLink(title="Refactoring Guru – Design Patterns", url="https://refactoring.guru/design-patterns/java", type="article"),
            ResourceLink(title="Head First Design Patterns", url="https://www.oreilly.com/library/view/head-first-design/0596007124/", type="course"),
            ResourceLink(title="Java Concurrency in Practice", url="https://www.youtube.com/watch?v=WH5UvQJizH0", type="video"),
        ],
        description="Object-oriented design in Java: SOLID, design patterns, and concurrency.",
        job_market_relevance="Required in 65% of senior Java engineering postings.",
        unlocks=["spring boot basics"],
    ),
    # ── GO ─────────────────────────────────────────────────────────────────────
    CourseModule(
        id="go-basics-010",
        title="Go Basics",
        skill_name="go",
        category="programming_language",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=[],
        learning_objectives=[
            "Understand Go syntax, types, and interfaces",
            "Use goroutines and channels for concurrency",
            "Write Go modules and manage dependencies",
            "Handle errors idiomatically in Go",
        ],
        resources=[
            ResourceLink(title="A Tour of Go", url="https://go.dev/tour/welcome/1", type="docs"),
            ResourceLink(title="Go by Example", url="https://gobyexample.com/", type="article"),
            ResourceLink(title="Golang Tutorial – TechWorld with Nana", url="https://www.youtube.com/watch?v=yyUHQIec83I", type="video"),
        ],
        description="Go programming language fundamentals: syntax, concurrency, and idioms.",
        job_market_relevance="Required in 43% of backend/DevOps engineering postings.",
        unlocks=["docker essentials", "kubernetes basics"],
    ),
    # ── REACT ──────────────────────────────────────────────────────────────────
    CourseModule(
        id="react-fund-011",
        title="React Fundamentals",
        skill_name="react",
        category="framework",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=["js-ess-004"],
        learning_objectives=[
            "Understand React component model and JSX",
            "Manage state with useState and useReducer",
            "Fetch data with useEffect",
            "Build reusable component libraries",
        ],
        resources=[
            ResourceLink(title="React Official Docs – Learn React", url="https://react.dev/learn", type="docs"),
            ResourceLink(title="React Full Course – Scrimba", url="https://scrimba.com/learn/learnreact", type="course"),
            ResourceLink(title="React in 100 Seconds – Fireship", url="https://www.youtube.com/watch?v=Tn6-PIqc4UM", type="video"),
        ],
        description="React fundamentals: components, hooks, state management, and data fetching.",
        job_market_relevance="Required in 76% of frontend engineering roles.",
        unlocks=["react advanced", "typescript basics"],
    ),
    CourseModule(
        id="react-adv-012",
        title="React Advanced",
        skill_name="react",
        category="framework",
        difficulty="Advanced",
        duration_hours=5.0,
        prerequisites=["react-fund-011", "ts-basics-005"],
        learning_objectives=[
            "Implement advanced patterns (compound components, render props)",
            "Optimize performance with useMemo and React.memo",
            "Manage complex state with Zustand or Jotai",
            "Integrate React Query for server state",
        ],
        resources=[
            ResourceLink(title="React Patterns – Kent C Dodds", url="https://epicreact.dev/", type="course"),
            ResourceLink(title="TkDodo's Blog – Practical React Query", url="https://tkdodo.eu/blog/practical-react-query", type="article"),
            ResourceLink(title="Jack Herrington – Advanced React", url="https://www.youtube.com/c/JackHerrington", type="video"),
        ],
        description="Advanced React: patterns, performance optimization, and state management.",
        job_market_relevance="Required in 58% of senior frontend engineering postings.",
        unlocks=[],
    ),
    # ── FASTAPI ────────────────────────────────────────────────────────────────
    CourseModule(
        id="fastapi-basics-013",
        title="FastAPI Basics",
        skill_name="fastapi",
        category="framework",
        difficulty="Beginner",
        duration_hours=3.0,
        prerequisites=["python-int-002"],
        learning_objectives=[
            "Build REST APIs with FastAPI",
            "Use Pydantic for data validation",
            "Implement dependency injection",
            "Generate automatic OpenAPI docs",
        ],
        resources=[
            ResourceLink(title="FastAPI Official Tutorial", url="https://fastapi.tiangolo.com/tutorial/", type="docs"),
            ResourceLink(title="FastAPI Full Course – Amigoscode", url="https://www.youtube.com/watch?v=7t2alSnE2-I", type="video"),
            ResourceLink(title="Building REST APIs with FastAPI", url="https://realpython.com/fastapi-python-web-apis/", type="article"),
        ],
        description="Build production-ready REST APIs with FastAPI, Pydantic validation, and auto docs.",
        job_market_relevance="Required in 49% of Python backend engineering roles.",
        unlocks=["fastapi advanced"],
    ),
    CourseModule(
        id="fastapi-adv-014",
        title="FastAPI Advanced",
        skill_name="fastapi",
        category="framework",
        difficulty="Advanced",
        duration_hours=4.0,
        prerequisites=["fastapi-basics-013"],
        learning_objectives=[
            "Add JWT authentication and OAuth2",
            "Build background tasks and WebSocket endpoints",
            "Write integration and unit tests for FastAPI",
            "Deploy FastAPI with Docker and NGINX",
        ],
        resources=[
            ResourceLink(title="FastAPI Advanced User Guide", url="https://fastapi.tiangolo.com/advanced/", type="docs"),
            ResourceLink(title="Full Stack FastAPI Template", url="https://github.com/tiangolo/full-stack-fastapi-template", type="article"),
            ResourceLink(title="TestDriven.io – FastAPI TDD", url="https://testdriven.io/blog/fastapi-crud/", type="article"),
        ],
        description="Advanced FastAPI: auth, testing, background tasks, and production deployment.",
        job_market_relevance="Required in 41% of senior Python backend postings.",
        unlocks=[],
    ),
    # ── DJANGO ─────────────────────────────────────────────────────────────────
    CourseModule(
        id="django-basics-015",
        title="Django Basics",
        skill_name="django",
        category="framework",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=["python-int-002", "sql-fund-006"],
        learning_objectives=[
            "Understand the Django MTV architecture",
            "Use the ORM for database operations",
            "Build forms and templates",
            "Implement Django REST Framework basics",
        ],
        resources=[
            ResourceLink(title="Django Official Tutorial", url="https://docs.djangoproject.com/en/stable/intro/tutorial01/", type="docs"),
            ResourceLink(title="CS50W – Web Programming with Python and JavaScript", url="https://cs50.harvard.edu/web/2020/", type="course"),
            ResourceLink(title="Django Full Course – Dennis Ivy", url="https://www.youtube.com/watch?v=PtQiiknWUcI", type="video"),
        ],
        description="Django web framework: ORM, views, templates, and REST Framework basics.",
        job_market_relevance="Required in 52% of Python full-stack web development roles.",
        unlocks=[],
    ),
    # ── NODE.JS ────────────────────────────────────────────────────────────────
    CourseModule(
        id="nodejs-fund-016",
        title="Node.js Fundamentals",
        skill_name="node.js",
        category="framework",
        difficulty="Beginner",
        duration_hours=3.0,
        prerequisites=["js-ess-004"],
        learning_objectives=[
            "Understand the Node.js event loop",
            "Build HTTP servers with Express.js",
            "Work with NPM and package.json",
            "Read/write files with the fs module",
        ],
        resources=[
            ResourceLink(title="Node.js Official Docs", url="https://nodejs.org/en/docs/", type="docs"),
            ResourceLink(title="Node.js Full Course – Traversy Media", url="https://www.youtube.com/watch?v=fBNz5xF-Kx4", type="video"),
            ResourceLink(title="The Odin Project – NodeJS", url="https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs", type="course"),
        ],
        description="Node.js fundamentals: event loop, Express.js, npm ecosystem, and file system.",
        job_market_relevance="Required in 69% of full-stack and backend JavaScript roles.",
        unlocks=["typescript basics"],
    ),
    # ── SPRING BOOT ────────────────────────────────────────────────────────────
    CourseModule(
        id="spring-basics-017",
        title="Spring Boot Basics",
        skill_name="spring boot",
        category="framework",
        difficulty="Intermediate",
        duration_hours=5.0,
        prerequisites=["java-oop-009"],
        learning_objectives=[
            "Bootstrap Spring Boot applications",
            "Build RESTful APIs with Spring MVC",
            "Use Spring Data JPA for persistence",
            "Implement Spring Security basics",
        ],
        resources=[
            ResourceLink(title="Spring Boot Official Docs", url="https://spring.io/projects/spring-boot", type="docs"),
            ResourceLink(title="Amigoscode – Spring Boot Tutorial", url="https://www.youtube.com/watch?v=9SGDpanrc8U", type="video"),
            ResourceLink(title="Baeldung – Spring Boot", url="https://www.baeldung.com/spring-boot", type="article"),
        ],
        description="Spring Boot: REST APIs, JPA persistence, and Spring Security fundamentals.",
        job_market_relevance="Required in 58% of Java enterprise backend roles.",
        unlocks=[],
    ),
    # ── REST API / GRAPHQL ──────────────────────────────────────────────────────
    CourseModule(
        id="rest-api-018",
        title="REST API Design",
        skill_name="rest api",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=2.5,
        prerequisites=["python-fund-001"],
        learning_objectives=[
            "Apply REST principles (stateless, resource-based URIs)",
            "Design versioned, paginated APIs",
            "Implement proper status codes and error responses",
            "Document APIs with OpenAPI/Swagger",
        ],
        resources=[
            ResourceLink(title="REST API Design Best Practices", url="https://www.freecodecamp.org/news/rest-api-best-practices-rest-endpoint-design-examples/", type="article"),
            ResourceLink(title="APIs for Beginners – freeCodeCamp", url="https://www.youtube.com/watch?v=GZvSYJDk-us", type="video"),
            ResourceLink(title="OpenAPI Specification", url="https://swagger.io/specification/", type="docs"),
        ],
        description="REST API design principles: versioning, pagination, error handling, and OpenAPI docs.",
        job_market_relevance="Required in 84% of backend engineering job postings.",
        unlocks=["graphql basics"],
    ),
    CourseModule(
        id="graphql-basics-019",
        title="GraphQL Basics",
        skill_name="graphql",
        category="framework",
        difficulty="Intermediate",
        duration_hours=3.0,
        prerequisites=["rest-api-018"],
        learning_objectives=[
            "Understand the GraphQL query language",
            "Build a GraphQL server with resolvers",
            "Use fragments, mutations, and subscriptions",
            "Integrate Apollo Client with React",
        ],
        resources=[
            ResourceLink(title="GraphQL Official Docs", url="https://graphql.org/learn/", type="docs"),
            ResourceLink(title="How to GraphQL", url="https://www.howtographql.com/", type="course"),
            ResourceLink(title="GraphQL with Apollo – Fireship", url="https://www.youtube.com/watch?v=BcLNfwF04Kw", type="video"),
        ],
        description="GraphQL fundamentals: schemas, resolvers, mutations, and Apollo Client.",
        job_market_relevance="Required in 38% of full-stack engineering postings.",
        unlocks=[],
    ),
    # ── DOCKER / KUBERNETES ─────────────────────────────────────────────────────
    CourseModule(
        id="docker-ess-020",
        title="Docker Essentials",
        skill_name="docker",
        category="tool",
        difficulty="Beginner",
        duration_hours=3.0,
        prerequisites=[],
        learning_objectives=[
            "Understand containers vs virtual machines",
            "Write Dockerfiles and build images",
            "Use Docker Compose for multi-service apps",
            "Push images to Docker Hub",
        ],
        resources=[
            ResourceLink(title="Docker Official Get Started Guide", url="https://docs.docker.com/get-started/", type="docs"),
            ResourceLink(title="Docker Tutorial – TechWorld with Nana", url="https://www.youtube.com/watch?v=3c-iBn73dDE", type="video"),
            ResourceLink(title="Play with Docker Classroom", url="https://training.play-with-docker.com/", type="course"),
        ],
        description="Docker fundamentals: containers, images, Dockerfile, and Docker Compose.",
        job_market_relevance="Required in 73% of backend and DevOps engineering roles.",
        unlocks=["kubernetes basics", "ci/cd pipelines"],
    ),
    CourseModule(
        id="k8s-basics-021",
        title="Kubernetes Basics",
        skill_name="kubernetes",
        category="tool",
        difficulty="Advanced",
        duration_hours=5.0,
        prerequisites=["docker-ess-020"],
        learning_objectives=[
            "Deploy applications using Pods, Deployments, and Services",
            "Configure ConfigMaps and Secrets",
            "Scale workloads with HPA",
            "Use kubectl to manage cluster resources",
        ],
        resources=[
            ResourceLink(title="Kubernetes Official Tutorial", url="https://kubernetes.io/docs/tutorials/kubernetes-basics/", type="docs"),
            ResourceLink(title="Kubernetes Full Course – TechWorld with Nana", url="https://www.youtube.com/watch?v=X48VuDVv0do", type="video"),
            ResourceLink(title="Kubernetes the Hard Way", url="https://github.com/kelseyhightower/kubernetes-the-hard-way", type="article"),
        ],
        description="Kubernetes orchestration: deployments, services, config management, and scaling.",
        job_market_relevance="Required in 57% of DevOps and senior backend engineering roles.",
        unlocks=[],
    ),
    CourseModule(
        id="cicd-022",
        title="CI/CD Pipelines",
        skill_name="ci/cd",
        category="tool",
        difficulty="Intermediate",
        duration_hours=3.0,
        prerequisites=["docker-ess-020"],
        learning_objectives=[
            "Build GitHub Actions workflows",
            "Automate tests, builds, and deployments",
            "Implement GitFlow branching strategy",
            "Set up environment secrets and approvals",
        ],
        resources=[
            ResourceLink(title="GitHub Actions Documentation", url="https://docs.github.com/en/actions", type="docs"),
            ResourceLink(title="CI/CD Full Course – TechWorld with Nana", url="https://www.youtube.com/watch?v=R8_veQiYBjI", type="video"),
            ResourceLink(title="GitLab CI/CD Tutorial", url="https://docs.gitlab.com/ee/ci/", type="docs"),
        ],
        description="CI/CD pipelines: GitHub Actions, automated testing, deployment, and GitFlow.",
        job_market_relevance="Required in 64% of backend and DevOps engineering postings.",
        unlocks=["kubernetes basics"],
    ),
    # ── CLOUD ───────────────────────────────────────────────────────────────────
    CourseModule(
        id="aws-basics-023",
        title="AWS Cloud Basics",
        skill_name="amazon web services",
        category="tool",
        difficulty="Beginner",
        duration_hours=4.0,
        prerequisites=[],
        learning_objectives=[
            "Navigate the AWS management console",
            "Deploy applications on EC2 and Elastic Beanstalk",
            "Use S3 for storage and CloudFront for CDN",
            "Configure IAM roles and policies",
        ],
        resources=[
            ResourceLink(title="AWS Training – Cloud Practitioner Essentials", url="https://aws.amazon.com/training/learn-about/cloud-practitioner/", type="course"),
            ResourceLink(title="AWS in 1 Hour – freeCodeCamp", url="https://www.youtube.com/watch?v=ulprqHHWlng", type="video"),
            ResourceLink(title="AWS Documentation", url="https://docs.aws.amazon.com/", type="docs"),
        ],
        description="AWS fundamentals: EC2, S3, IAM, Elastic Beanstalk, and core cloud concepts.",
        job_market_relevance="Required in 68% of backend engineering roles.",
        unlocks=["kubernetes basics", "ci/cd pipelines"],
    ),
    CourseModule(
        id="gcp-basics-024",
        title="GCP Basics",
        skill_name="google cloud platform",
        category="tool",
        difficulty="Beginner",
        duration_hours=3.5,
        prerequisites=[],
        learning_objectives=[
            "Use Google Cloud Console and gcloud CLI",
            "Deploy services on Cloud Run and App Engine",
            "Store data in Cloud Storage and Firestore",
            "Configure GCP IAM",
        ],
        resources=[
            ResourceLink(title="Google Cloud Skills Boost", url="https://cloudskillsboost.google/", type="course"),
            ResourceLink(title="GCP in 1 Hour – TechWorld with Nana", url="https://www.youtube.com/watch?v=IU-BRUzn0aw", type="video"),
            ResourceLink(title="GCP Documentation", url="https://cloud.google.com/docs", type="docs"),
        ],
        description="GCP fundamentals: Cloud Run, App Engine, Cloud Storage, Firestore, and IAM.",
        job_market_relevance="Required in 45% of cloud engineering and data science roles.",
        unlocks=[],
    ),
    # ── MACHINE LEARNING ────────────────────────────────────────────────────────
    CourseModule(
        id="ml-fund-025",
        title="ML Fundamentals",
        skill_name="machine learning",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=5.0,
        prerequisites=["python-fund-001", "statistics for ds"],
        learning_objectives=[
            "Understand supervised and unsupervised learning",
            "Implement linear and logistic regression",
            "Evaluate models with cross-validation",
            "Preprocess data and handle missing values",
        ],
        resources=[
            ResourceLink(title="Andrew Ng – Machine Learning Specialization", url="https://www.coursera.org/specializations/machine-learning-introduction", type="course"),
            ResourceLink(title="Scikit-learn Official Docs", url="https://scikit-learn.org/stable/user_guide.html", type="docs"),
            ResourceLink(title="StatQuest with Josh Starmer", url="https://www.youtube.com/c/joshstarmer", type="video"),
        ],
        description="Machine learning fundamentals: supervised/unsupervised learning, model evaluation, and preprocessing.",
        job_market_relevance="Required in 71% of data science and ML engineering postings.",
        unlocks=["supervised learning", "deep learning basics", "nlp fundamentals"],
    ),
    CourseModule(
        id="supervised-026",
        title="Supervised Learning",
        skill_name="supervised learning",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=4.0,
        prerequisites=["ml-fund-025"],
        learning_objectives=[
            "Implement decision trees and random forests",
            "Use gradient boosting (XGBoost, LightGBM)",
            "Apply SVM and k-NN classifiers",
            "Tune hyperparameters with grid and random search",
        ],
        resources=[
            ResourceLink(title="Hands-On ML with Scikit-Learn – O'Reilly", url="https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/", type="course"),
            ResourceLink(title="Kaggle – Intro to Machine Learning", url="https://www.kaggle.com/learn/intro-to-machine-learning", type="course"),
            ResourceLink(title="XGBoost Documentation", url="https://xgboost.readthedocs.io/en/stable/", type="docs"),
        ],
        description="Supervised learning algorithms: decision trees, boosting, SVM, and hyperparameter tuning.",
        job_market_relevance="Required in 63% of ML engineering and data science roles.",
        unlocks=["deep learning basics"],
    ),
    CourseModule(
        id="dl-basics-027",
        title="Deep Learning Basics",
        skill_name="deep learning",
        category="domain_knowledge",
        difficulty="Advanced",
        duration_hours=6.0,
        prerequisites=["supervised-026"],
        learning_objectives=[
            "Build neural networks with PyTorch",
            "Train CNNs for image classification",
            "Implement RNNs and LSTMs",
            "Use transfer learning with pre-trained models",
        ],
        resources=[
            ResourceLink(title="fast.ai Practical Deep Learning", url="https://course.fast.ai/", type="course"),
            ResourceLink(title="PyTorch Official Tutorials", url="https://pytorch.org/tutorials/", type="docs"),
            ResourceLink(title="3Blue1Brown – Neural Networks", url="https://www.youtube.com/playlist?list=PLZHQObOWTQDNU6R1_67000Dx_ZCJB-3pi", type="video"),
        ],
        description="Deep learning: neural networks, CNNs, RNNs, and transfer learning with PyTorch.",
        job_market_relevance="Required in 55% of ML engineer and AI researcher postings.",
        unlocks=["nlp fundamentals", "llm api integration"],
    ),
    # ── NLP / LLM ───────────────────────────────────────────────────────────────
    CourseModule(
        id="nlp-fund-028",
        title="NLP Fundamentals",
        skill_name="natural language processing",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=4.0,
        prerequisites=["ml-fund-025"],
        learning_objectives=[
            "Apply tokenization, stemming, and lemmatization",
            "Use TF-IDF and word embeddings",
            "Fine-tune BERT for classification tasks",
            "Build text classification pipelines",
        ],
        resources=[
            ResourceLink(title="HuggingFace NLP Course", url="https://huggingface.co/learn/nlp-course/chapter1/1", type="course"),
            ResourceLink(title="NLTK Book", url="https://www.nltk.org/book/", type="article"),
            ResourceLink(title="Andrej Karpathy – Let's Build GPT", url="https://www.youtube.com/watch?v=kCc8FmEb1nY", type="video"),
        ],
        description="NLP fundamentals: tokenization, embeddings, BERT fine-tuning, and text pipelines.",
        job_market_relevance="Required in 52% of NLP engineer and data science postings.",
        unlocks=["llm api integration", "vector databases"],
    ),
    CourseModule(
        id="llm-api-029",
        title="LLM API Integration",
        skill_name="llm api integration",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=3.0,
        prerequisites=["python-int-002"],
        learning_objectives=[
            "Integrate OpenAI and Gemini APIs",
            "Apply prompt engineering techniques",
            "Build retrieval-augmented generation (RAG) pipelines",
            "Handle rate limits, retries, and streaming",
        ],
        resources=[
            ResourceLink(title="OpenAI API Documentation", url="https://platform.openai.com/docs/introduction", type="docs"),
            ResourceLink(title="xAI Grok API Docs", url="https://docs.x.ai/", type="docs"),
            ResourceLink(title="LangChain Docs", url="https://python.langchain.com/docs/get_started/introduction", type="docs"),
        ],
        description="Integrating LLM APIs: prompt engineering, RAG pipelines, and production patterns.",
        job_market_relevance="Required in 59% of AI engineering and full-stack AI application roles.",
        unlocks=["vector databases"],
    ),
    CourseModule(
        id="vector-db-030",
        title="Vector Databases",
        skill_name="vector databases",
        category="tool",
        difficulty="Intermediate",
        duration_hours=2.5,
        prerequisites=["llm-api-029"],
        learning_objectives=[
            "Understand embedding spaces and similarity search",
            "Use Pinecone or Chroma for vector storage",
            "Build semantic search with embeddings",
            "Integrate vector search into RAG applications",
        ],
        resources=[
            ResourceLink(title="Pinecone Learn – Vector Databases 101", url="https://www.pinecone.io/learn/vector-database/", type="article"),
            ResourceLink(title="Chroma Getting Started", url="https://docs.trychroma.com/getting-started", type="docs"),
            ResourceLink(title="Vector Databases Explained – Fireship", url="https://www.youtube.com/watch?v=klTvEwg3oJ4", type="video"),
        ],
        description="Vector databases: embeddings, similarity search, Pinecone, Chroma, and RAG.",
        job_market_relevance="Required in 44% of AI engineering postings.",
        unlocks=[],
    ),
    # ── DATA SCIENCE TOOLS ───────────────────────────────────────────────────────
    CourseModule(
        id="pandas-numpy-031",
        title="Pandas & NumPy",
        skill_name="pandas & numpy",
        category="tool",
        difficulty="Beginner",
        duration_hours=3.5,
        prerequisites=["python-fund-001"],
        learning_objectives=[
            "Manipulate DataFrames with pandas",
            "Perform vectorized operations with NumPy",
            "Clean and reshape datasets",
            "Merge, group, and pivot data",
        ],
        resources=[
            ResourceLink(title="Pandas Official Documentation", url="https://pandas.pydata.org/docs/getting_started/index.html", type="docs"),
            ResourceLink(title="NumPy Official Quickstart", url="https://numpy.org/doc/stable/user/quickstart.html", type="docs"),
            ResourceLink(title="Kaggle – Pandas Course", url="https://www.kaggle.com/learn/pandas", type="course"),
        ],
        description="Data manipulation with Pandas and NumPy: DataFrames, vectorization, and data cleaning.",
        job_market_relevance="Required in 78% of data science and analytics engineering roles.",
        unlocks=["data visualization", "ml fundamentals"],
    ),
    CourseModule(
        id="dataviz-032",
        title="Data Visualization",
        skill_name="data visualization",
        category="tool",
        difficulty="Beginner",
        duration_hours=2.5,
        prerequisites=["pandas-numpy-031"],
        learning_objectives=[
            "Create charts with Matplotlib and Seaborn",
            "Build interactive dashboards with Plotly",
            "Choose appropriate chart types for data",
            "Apply visualization best practices",
        ],
        resources=[
            ResourceLink(title="Matplotlib Official Tutorials", url="https://matplotlib.org/stable/tutorials/index.html", type="docs"),
            ResourceLink(title="Plotly Python Docs", url="https://plotly.com/python/", type="docs"),
            ResourceLink(title="Data Visualization Best Practices", url="https://www.kaggle.com/learn/data-visualization", type="course"),
        ],
        description="Data visualization: Matplotlib, Seaborn, Plotly, and dashboard design.",
        job_market_relevance="Required in 66% of data science and analytics roles.",
        unlocks=[],
    ),
    CourseModule(
        id="stats-ds-033",
        title="Statistics for DS",
        skill_name="statistics for ds",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=4.0,
        prerequisites=["pandas-numpy-031"],
        learning_objectives=[
            "Apply descriptive and inferential statistics",
            "Use hypothesis testing (t-test, chi-square, ANOVA)",
            "Understand Bayesian probability basics",
            "Perform A/B test analysis",
        ],
        resources=[
            ResourceLink(title="Khan Academy – Statistics and Probability", url="https://www.khanacademy.org/math/statistics-probability", type="course"),
            ResourceLink(title="Think Stats – Allen B. Downey", url="https://greenteapress.com/thinkstats2/html/index.html", type="article"),
            ResourceLink(title="StatQuest – Statistics Fundamentals", url="https://www.youtube.com/playlist?list=PLblh5JKOoLUK0FLuzwntyYI10UQFUhsY9", type="video"),
        ],
        description="Statistics for data science: hypothesis testing, probability, and A/B testing.",
        job_market_relevance="Required in 69% of data science job postings.",
        unlocks=["ml fundamentals"],
    ),
    # ── SYSTEM DESIGN ───────────────────────────────────────────────────────────
    CourseModule(
        id="sysdesign-fund-034",
        title="System Design Fundamentals",
        skill_name="system design",
        category="domain_knowledge",
        difficulty="Intermediate",
        duration_hours=4.0,
        prerequisites=["rest-api-018"],
        learning_objectives=[
            "Design scalable distributed systems",
            "Apply CAP theorem and consistency models",
            "Use load balancers, caches, and message queues",
            "Draw system architecture diagrams",
        ],
        resources=[
            ResourceLink(title="System Design Primer – GitHub", url="https://github.com/donnemartin/system-design-primer", type="article"),
            ResourceLink(title="ByteByteGo – System Design Interview", url="https://www.youtube.com/c/ByteByteGo", type="video"),
            ResourceLink(title="Grokking the System Design Interview", url="https://www.educative.io/courses/grokking-the-system-design-interview", type="course"),
        ],
        description="System design fundamentals: scalability, CAP theorem, caching, and load balancing.",
        job_market_relevance="Required in 72% of senior backend and full-stack engineering roles.",
        unlocks=["system design advanced"],
    ),
    CourseModule(
        id="sysdesign-adv-035",
        title="System Design Advanced",
        skill_name="system design",
        category="domain_knowledge",
        difficulty="Advanced",
        duration_hours=5.0,
        prerequisites=["sysdesign-fund-034"],
        learning_objectives=[
            "Design event-driven architectures with Kafka",
            "Implement microservices patterns",
            "Design for high availability and disaster recovery",
            "Conduct capacity planning and estimation",
        ],
        resources=[
            ResourceLink(title="Designing Data-Intensive Applications – Martin Kleppmann", url="https://dataintensive.net/", type="course"),
            ResourceLink(title="Martin Fowler – Microservices", url="https://martinfowler.com/articles/microservices.html", type="article"),
            ResourceLink(title="Alex Xu – System Design Interview Vol 2", url="https://www.youtube.com/watch?v=bUHFg8CZFws", type="video"),
        ],
        description="Advanced system design: event-driven architecture, microservices, HA, and capacity planning.",
        job_market_relevance="Required in 61% of senior backend and principal engineer postings.",
        unlocks=[],
    ),
    # ── NON-TECHNICAL ───────────────────────────────────────────────────────────
    CourseModule(
        id="tech-comm-036",
        title="Technical Communication",
        skill_name="technical communication",
        category="soft_skill",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Write clear technical documentation and ADRs",
            "Present technical concepts to non-technical audiences",
            "Structure effective emails and Slack messages",
            "Create onboarding guides and runbooks",
        ],
        resources=[
            ResourceLink(title="Google Technical Writing Courses", url="https://developers.google.com/tech-writing", type="course"),
            ResourceLink(title="Divio Documentation System", url="https://documentation.divio.com/", type="article"),
            ResourceLink(title="Writing for Engineers – freeCodeCamp", url="https://www.freecodecamp.org/news/technical-writing-for-developers/", type="article"),
        ],
        description="Technical communication: documentation, ADRs, runbooks, and presenting to stakeholders.",
        job_market_relevance="Required in 81% of senior and leadership engineering postings.",
        unlocks=["stakeholder management", "presentation skills"],
    ),
    CourseModule(
        id="agile-037",
        title="Agile & Scrum Fundamentals",
        skill_name="agile",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Apply Scrum ceremonies (sprint planning, retros, standups)",
            "Write effective user stories and acceptance criteria",
            "Work with Jira and kanban boards",
            "Understand Agile values and principles",
        ],
        resources=[
            ResourceLink(title="Scrum Guide 2020", url="https://scrumguides.org/scrum-guide.html", type="docs"),
            ResourceLink(title="Atlassian – Agile Coach", url="https://www.atlassian.com/agile", type="article"),
            ResourceLink(title="Scrum in 20 mins – Fireship", url="https://www.youtube.com/watch?v=SWDhGSZNF9M", type="video"),
        ],
        description="Agile and Scrum: ceremonies, user stories, Jira workflows, and Agile principles.",
        job_market_relevance="Required in 77% of software engineering and product roles.",
        unlocks=["project management basics", "stakeholder management"],
    ),
    CourseModule(
        id="pm-basics-038",
        title="Project Management Basics",
        skill_name="project management",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=3.0,
        prerequisites=["agile-037"],
        learning_objectives=[
            "Apply PMI/CAPM project lifecycle phases",
            "Build project charters and WBS",
            "Manage risk registers and mitigation plans",
            "Track projects with Gantt charts",
        ],
        resources=[
            ResourceLink(title="PMI CAPM Exam Prep – PMI.org", url="https://www.pmi.org/certifications/certified-associate-capm", type="docs"),
            ResourceLink(title="Google Project Management Certificate", url="https://www.coursera.org/professional-certificates/google-project-management", type="course"),
            ResourceLink(title="Project Management Tutorial – Simplilearn", url="https://www.youtube.com/watch?v=ZKOL-rZ79gs", type="video"),
        ],
        description="Project management fundamentals: PMI lifecycle, risk management, and Gantt planning.",
        job_market_relevance="Required in 62% of program manager and tech lead postings.",
        unlocks=["stakeholder management"],
    ),
    CourseModule(
        id="customer-svc-039",
        title="Customer Service Excellence",
        skill_name="customer service",
        category="soft_skill",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Apply active listening and empathy techniques",
            "Handle complaints and escalations professionally",
            "Use CRM tools for customer tracking",
            "Measure CSAT, NPS, and service KPIs",
        ],
        resources=[
            ResourceLink(title="HubSpot – Customer Service Training", url="https://academy.hubspot.com/courses/customer-service-training", type="course"),
            ResourceLink(title="Zendesk Customer Service Blog", url="https://www.zendesk.com/blog/customer-service/", type="article"),
            ResourceLink(title="Customer Service Mastery – Udemy", url="https://www.udemy.com/course/customer-service-mastery/", type="course"),
        ],
        description="Customer service excellence: active listening, complaint handling, CRM, and service KPIs.",
        job_market_relevance="Required in 88% of customer-facing and support roles.",
        unlocks=["conflict resolution"],
    ),
    CourseModule(
        id="conflict-res-040",
        title="Conflict Resolution",
        skill_name="conflict resolution",
        category="soft_skill",
        difficulty="Beginner",
        duration_hours=1.5,
        prerequisites=["customer-svc-039"],
        learning_objectives=[
            "Apply Thomas-Kilmann conflict styles framework",
            "Use de-escalation techniques",
            "Facilitate constructive disagreements in teams",
            "Document and resolve workplace grievances",
        ],
        resources=[
            ResourceLink(title="Harvard PON – Conflict Resolution", url="https://www.pon.harvard.edu/daily/conflict-resolution/", type="article"),
            ResourceLink(title="Conflict Management – LinkedIn Learning", url="https://www.linkedin.com/learning/conflict-management", type="course"),
            ResourceLink(title="How to Resolve Conflict – TED Talk", url="https://www.ted.com/talks/daniel_shapiro_how_to_resolve_conflicts", type="video"),
        ],
        description="Conflict resolution: de-escalation, team facilitation, and constructive disagreement.",
        job_market_relevance="Required in 73% of people management and HR postings.",
        unlocks=[],
    ),
    CourseModule(
        id="hipaa-041",
        title="Healthcare Compliance Basics",
        skill_name="healthcare compliance",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Understand HIPAA Privacy and Security Rules",
            "Identify PHI and handle it correctly",
            "Complete HIPAA training requirements",
            "Understand HITECH Act implications",
        ],
        resources=[
            ResourceLink(title="HHS – HIPAA for Professionals", url="https://www.hhs.gov/hipaa/for-professionals/index.html", type="docs"),
            ResourceLink(title="HIPAA Training – Coursera", url="https://www.coursera.org/learn/healthcare-law", type="course"),
            ResourceLink(title="HIPAA Explained – YouTube", url="https://www.youtube.com/watch?v=3d3nxHq9MHs", type="video"),
        ],
        description="HIPAA and HITECH compliance: PHI handling, privacy rules, and training requirements.",
        job_market_relevance="Required in 91% of healthcare IT and clinical operations roles.",
        unlocks=["data privacy & gdpr basics"],
    ),
    CourseModule(
        id="retail-ops-042",
        title="Retail Operations & SOP",
        skill_name="retail operations",
        category="operational",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Follow standard operating procedures for retail",
            "Manage inventory with FIFO and shrinkage controls",
            "Process POS transactions and returns",
            "Understand loss prevention fundamentals",
        ],
        resources=[
            ResourceLink(title="NRF – Retail Training Resources", url="https://nrf.com/resources/retailing-fundamentals", type="docs"),
            ResourceLink(title="Retail Management – Coursera", url="https://www.coursera.org/learn/retail-management", type="course"),
            ResourceLink(title="Retail Operations Guide – Shopify", url="https://www.shopify.com/retail/retail-operations", type="article"),
        ],
        description="Retail operations: SOPs, inventory management, POS, and loss prevention.",
        job_market_relevance="Required in 85% of retail operations and store management roles.",
        unlocks=["customer service"],
    ),
    CourseModule(
        id="warehouse-043",
        title="Warehouse Safety & SOPs",
        skill_name="warehouse operations",
        category="operational",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Follow OSHA safety standards in warehouse environments",
            "Operate forklifts and pallet jacks safely",
            "Apply 5S workplace organization methodology",
            "Manage inbound and outbound logistics SOPs",
        ],
        resources=[
            ResourceLink(title="OSHA Warehousing Safety Guidelines", url="https://www.osha.gov/warehousing", type="docs"),
            ResourceLink(title="Warehouse Safety Training – Coursera", url="https://www.coursera.org/courses?query=warehouse+safety", type="course"),
            ResourceLink(title="5S Methodology Explained", url="https://www.youtube.com/watch?v=1RKBdCnzT10", type="video"),
        ],
        description="Warehouse safety: OSHA standards, forklift operation, 5S methodology, and logistics SOPs.",
        job_market_relevance="Required in 94% of warehouse operations and logistics roles.",
        unlocks=[],
    ),
    CourseModule(
        id="fin-literacy-044",
        title="Financial Literacy for Non-Finance",
        skill_name="financial literacy",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=2.5,
        prerequisites=[],
        learning_objectives=[
            "Read and interpret income statements and balance sheets",
            "Understand budgeting and cost center management",
            "Apply ROI and NPV analysis basics",
            "Navigate accounts payable/receivable workflows",
        ],
        resources=[
            ResourceLink(title="Financial Literacy – Khan Academy", url="https://www.khanacademy.org/college-careers-more/financial-literacy", type="course"),
            ResourceLink(title="Accounting Fundamentals – Coursera", url="https://www.coursera.org/learn/accounting-fundamentals", type="course"),
            ResourceLink(title="Financial Statements Explained – YouTube", url="https://www.youtube.com/watch?v=uVJ8K9lZCWo", type="video"),
        ],
        description="Financial literacy: reading financial statements, budgeting, ROI analysis, and AP/AR.",
        job_market_relevance="Required in 71% of operations manager and business analyst roles.",
        unlocks=["project management basics"],
    ),
    CourseModule(
        id="hr-fund-045",
        title="HR Fundamentals",
        skill_name="human resources",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=2.5,
        prerequisites=[],
        learning_objectives=[
            "Understand recruitment, onboarding, and offboarding processes",
            "Apply performance review frameworks (OKRs, 360 reviews)",
            "Know employment law basics (FLSA, EEO, ADA)",
            "Use HRIS systems for employee data management",
        ],
        resources=[
            ResourceLink(title="SHRM – HR Certification Prep", url="https://www.shrm.org/certification", type="course"),
            ResourceLink(title="HR Fundamentals – Coursera", url="https://www.coursera.org/learn/human-resources-fundamentals", type="course"),
            ResourceLink(title="SHRM HR Knowledge Center", url="https://www.shrm.org/resourcesandtools/tools-and-samples/hr-qa/", type="article"),
        ],
        description="HR fundamentals: recruitment, performance management, employment law, and HRIS.",
        job_market_relevance="Required in 89% of HR generalist and people operations roles.",
        unlocks=["conflict resolution", "leadership fundamentals"],
    ),
    CourseModule(
        id="biz-writing-046",
        title="Business Writing",
        skill_name="business writing",
        category="soft_skill",
        difficulty="Beginner",
        duration_hours=1.5,
        prerequisites=[],
        learning_objectives=[
            "Write clear, concise professional emails",
            "Structure executive summaries and reports",
            "Apply the Pyramid Principle for business communication",
            "Proofread and edit business documents",
        ],
        resources=[
            ResourceLink(title="Business Writing – Coursera (UC Boulder)", url="https://www.coursera.org/learn/writing-for-business", type="course"),
            ResourceLink(title="Purdue OWL – Business Writing", url="https://owl.purdue.edu/owl/subject_specific_writing/professional_technical_writing/", type="article"),
            ResourceLink(title="HBR – How to Write Better Emails", url="https://hbr.org/2016/11/how-to-write-email-with-military-precision", type="article"),
        ],
        description="Business writing: professional emails, executive summaries, and the Pyramid Principle.",
        job_market_relevance="Required in 86% of business analyst and operations roles.",
        unlocks=["technical communication", "presentation skills"],
    ),
    CourseModule(
        id="stakeholder-047",
        title="Stakeholder Management",
        skill_name="stakeholder management",
        category="soft_skill",
        difficulty="Intermediate",
        duration_hours=2.0,
        prerequisites=["biz-writing-046"],
        learning_objectives=[
            "Map stakeholders by influence and interest",
            "Create communication plans for diverse audiences",
            "Manage expectations and conflicting priorities",
            "Build consensus and facilitate decision-making",
        ],
        resources=[
            ResourceLink(title="PMI – Stakeholder Engagement", url="https://www.pmi.org/learning/library/stakeholder-engagement-tools-techniques-5798", type="article"),
            ResourceLink(title="Stakeholder Management – LinkedIn Learning", url="https://www.linkedin.com/learning/stakeholder-management", type="course"),
            ResourceLink(title="Managing Up and Across – HBR", url="https://hbr.org/2020/01/how-to-build-relationships-with-senior-leaders", type="article"),
        ],
        description="Stakeholder management: mapping, communication plans, consensus building, and prioritization.",
        job_market_relevance="Required in 74% of project manager and product manager postings.",
        unlocks=[],
    ),
    CourseModule(
        id="gdpr-048",
        title="Data Privacy & GDPR Basics",
        skill_name="data privacy",
        category="domain_knowledge",
        difficulty="Beginner",
        duration_hours=2.0,
        prerequisites=[],
        learning_objectives=[
            "Understand GDPR principles and legal bases for processing",
            "Handle data subject rights (access, erasure, portability)",
            "Conduct Data Protection Impact Assessments (DPIA)",
            "Implement privacy by design principles",
        ],
        resources=[
            ResourceLink(title="ICO – Guide to GDPR", url="https://ico.org.uk/for-organisations/guide-to-data-protection/guide-to-the-general-data-protection-regulation-gdpr/", type="docs"),
            ResourceLink(title="GDPR for Developers – Coursera", url="https://www.coursera.org/learn/gdpr", type="course"),
            ResourceLink(title="GDPR Explained – YouTube", url="https://www.youtube.com/watch?v=j6WWBp7JXJM", type="video"),
        ],
        description="GDPR and data privacy: processing principles, data subject rights, DPIA, and privacy by design.",
        job_market_relevance="Required in 61% of engineering and compliance roles in the EU.",
        unlocks=[],
    ),
    CourseModule(
        id="presentation-049",
        title="Presentation Skills",
        skill_name="presentation skills",
        category="soft_skill",
        difficulty="Beginner",
        duration_hours=1.5,
        prerequisites=["biz-writing-046"],
        learning_objectives=[
            "Design compelling slide decks using storytelling",
            "Deliver presentations with confidence and pacing",
            "Handle Q&A sessions professionally",
            "Use data visualization in presentations effectively",
        ],
        resources=[
            ResourceLink(title="Presentation Skills – Coursera (U Michigan)", url="https://www.coursera.org/learn/public-speaking", type="course"),
            ResourceLink(title="TED Talk – The Secret Structure of Great Talks", url="https://www.ted.com/talks/nancy_duarte_the_secret_structure_of_great_talks", type="video"),
            ResourceLink(title="Canva Presentation Tips", url="https://www.canva.com/learn/presentation-tips/", type="article"),
        ],
        description="Presentation skills: storytelling, slide design, delivery, and Q&A handling.",
        job_market_relevance="Required in 79% of leadership and senior individual contributor postings.",
        unlocks=[],
    ),
    CourseModule(
        id="leadership-050",
        title="Leadership Fundamentals",
        skill_name="leadership",
        category="soft_skill",
        difficulty="Intermediate",
        duration_hours=3.0,
        prerequisites=["agile-037", "hr-fund-045"],
        learning_objectives=[
            "Apply situational leadership styles",
            "Give and receive feedback using the SBI framework",
            "Build psychological safety in teams",
            "Coach and mentor junior team members",
        ],
        resources=[
            ResourceLink(title="Harvard ManageMentor – Leadership", url="https://online.hbs.edu/courses/leadership-principles/", type="course"),
            ResourceLink(title="Dare to Lead – Brené Brown Summary", url="https://brenebrown.com/hubs/dare-to-lead/", type="article"),
            ResourceLink(title="Leadership Fundamentals – LinkedIn Learning", url="https://www.linkedin.com/learning/leadership-foundations", type="course"),
        ],
        description="Leadership fundamentals: situational leadership, feedback, psychological safety, and coaching.",
        job_market_relevance="Required in 83% of engineering manager and tech lead postings.",
        unlocks=["stakeholder management"],
    ),
]


def get_catalog() -> list[CourseModule]:
    return COURSE_CATALOG


def get_module_by_id(module_id: str) -> CourseModule | None:
    for m in COURSE_CATALOG:
        if m.id == module_id:
            return m
    return None
